# -*- coding: utf-8 -*-
"""Git Hub - Global Energy Sustainability ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cYSdj97h-aWsIn9JbzQ0dP3fhKn8IUNd

Modules Used for Preliminary analysis
"""

import numpy as np
import pandas as pd
from google.colab import files
uploaded = files.upload()
import matplotlib.pyplot as plt

"""Importing the dataset & Showcase"""

path = '/content/global-data-on-sustainable-energy.csv'
SustainEnergyData = pd.read_csv(path)
SustainEnergyData.head(5)

"""Getting Info on Value Types"""

SustainEnergyData.info()

"""Shape of the Dataframe"""

SustainEnergyData.shape

"""Description of the Dataframe"""

SustainEnergyData.describe().transpose()

"""Finding the Null Values"""

SustainEnergyData.isnull().sum()

SustainEnergyData_MissingValues = SustainEnergyData.isnull().sum() / SustainEnergyData.shape[0] * 100.00
print(round(SustainEnergyData_MissingValues),2)

SustainEnergyData.isna().sum().plot(kind = 'bar')

"""How it should be formatted:

introduction/ abstract

pargraph on where is in the landscape

summarize docs that I've read. Not techniques but the research questions and related studies  

the data set description

data dictionary

number of obs
missing value

Histogram shows null values

Data distribution in bar chart

Records per year

country breakdown

Road map - can be vague but it has to be timeline


Also need to use pandas profiling from cind 119 python help sklearn tutorial

---

# I am worried about the percentage if I am doing regression

---

Correlation to Check it
"""

SustainEnergyData.corr()

SustainEnergyData.corr()['Value_co2_emissions_kt_by_country']

SustainEnergyData['Year'].count()

SustainEnergyData.groupby('Year').count()

SustainEnergyData.groupby('Entity').count()

"""# Profiling"""

!pip install pydantic
!pip install PyYAML
!pip install jinja2
!pip install visions
!pip install htmlmin
!pip install phik
!pip install requests
!pip install tqdm
!pip install seaborn
!pip install multimethod
!pip install statsmodels
!pip install typeguard
!pip install imagehash
!pip install wordcloud
!pip install dacite
!pip install numba

import sys
!{sys.executable} -m pip install -U ydata-profiling
!jupyter nbextension enable --py widgetsnbextension

from ydata_profiling import ProfileReport

prof = ProfileReport(SustainEnergyData)
prof